name: Website

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [remote-trigger]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "./site"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Generate
        run: |
          pip install -r requirements.txt --break-system-packages
          npm --prefix site i starlight-theme-obsidian
          python3 generate.py

      - name: Install, build, and upload your site
        uses: withastro/action@v5
        with:
          path: ./site



  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

